language: java
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
jdk:
  - openjdk11
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
install:
  - mvn --settings .travis/settings.xml clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
deploy:
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: sbtqa/video-recorder
      branch: master
      jdk: openjdk11
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: sbtqa/video-recorder
      tags: true
      jdk: openjdk11
notifications:
  email: false
  slack:
    rooms:
      - secure: i7YQFSbVbPxFzNfLKujJDIHk3hDTu/2WEFHXrc7SdUYO06pE1ThD1OQScoc5dzF2o9VCM8GWCTbmCecl+zOc5IkMgae/QZ+4jsnY3LgwkJ6CcU0PN+UmffCSTX9RFQwAQWPSzTg8unYAsWD8dh6hsv/6/XF20jq0xgEuvK9YEnhWvSdi6zOiz3E1wXDgzZYztYNPwCOizvURqTcvFkT8IppBXu829Hrjaorj7Kq1kGGN6L9mFGX8tCKWI14BRAwrCNBM7qnymT+M+hYUGTKXGxLC53Nwy4GqOcN6XK1PbZ00WZbIBTzdIRbrezfHtj0dHYZXu9warZiWjBGxChhdwE7OMI0bsjouc5C1GodbCVBp/Pvmxxgys6YLlY9oTASAbKD0ua4xrYkikXlF+ECyJLESsMSo6FXFqU4Qw+9grm3q88kxmbFyTavmGvgnwDlsC/sNxnfTocG/Cedr5IYN6AkSi/BnwpMPb69nl1ZzsQL6997fUwb4WLVUeX6llNXjAluSixymgKRulRIxA+Qk3Dkb3tWlDqdrERnPKuGoaCanF1D24LS8Fx5S0mLqEa3EbR38xj94TksAl38VTyc/d9VZ6YYHyZS7BwiWadmDabBX2ZdRWNhkGD7nqIlBs8eAhJw0OcSAXDkGMLKqnLQBvHS9GHh7XJrLc2WQVOFNlnc=
    template:
      - "Build status: %{message}"
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"